select * from customer_table;
-- Business Questions 
-- 1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as total_revenue
from customer_table
group by gender;

-- 2. Which customers used a discount but still spent more than the average purchase?
select customer_id, purchase_amount
from customer_table
where purchase_amount > (select avg(purchase_amount) from customer_table) and discount_applied = 'Yes';

-- 3. Which are the top 5 products with the highest average rating?
select item_purchased, round(avg(review_rating),2) as "Average_product_rating"
from customer_table
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. Compare the average purchase amounts between highest standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) as Avg_purchase_amount
from customer_table
where shipping_type in ('Express','Standard')
group by shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers, avg(purchase_amount) as Avg_purchase_amount, 
sum(purchase_amount) as total_revenue
from customer_table
group by subscription_status;

select * from customer_table;
-- 6.which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*) *100 , 2) as discount_rate
from customer_table
group by item_purchased
order by discount_rate desc
limit 5;
 
-- 7. Segment customers, into New, Returning, Loyal based on the total
--    number of previous purchases and show the count of each segement.
with customer_type as (
select customer_id, previous_purchases, 
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal' end as customer_segment 
from customer_table
)
select customer_segment, count(*) as 'No_of_customers'
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category
with item_counts as (
select item_purchased, 
category, 
count(customer_id) as total_orders,
-- here we used window function row number
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_table
group by category, item_purchased
)
select item_rank, 
category,
item_purchased,
total_orders
from item_counts
where item_rank <= 3;


-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer_table
where previous_purchases > 5
group by subscription_status;


-- 10. What is the revenue contribution for each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer_table
group by age_group
order by total_revenue desc;